# Autogenerated by `bun2nix`; editing manually is not recommended
# Compact package and cache-group plan for Bun workspaces
{
copyPathToStore,
fetchFromGitHub,
fetchgit,
fetchurl,
...
}:
let
row = resolution: source: os: cpu: registry: [ resolution source os cpu registry ];
npm = name: version: hash: os: cpu:
row "${name}@${version}" (fetchurl {
url = "https://registry.npmjs.org/${name}/-/${builtins.baseNameOf name}-${version}.tgz";
inherit hash;
}) os cpu null;
url = resolution: sourceUrl: name: hash: os: cpu: registry:
row resolution (fetchurl ({ url = sourceUrl; inherit hash; }
// (if name == null then { } else { inherit name; }))) os cpu registry;
git = resolution: sourceUrl: rev: hash: os: cpu:
row resolution (fetchgit { url = sourceUrl; inherit rev hash; }) os cpu null;
github = resolution: owner: repo: rev: hash: os: cpu:
row resolution (fetchFromGitHub { inherit owner repo rev hash; }) os cpu null;
tarball = resolution: sourceUrl: hash: os: cpu:
row resolution (builtins.fetchTarball { url = sourceUrl; sha256 = hash; }) os cpu null;
path = resolution: sourcePath: os: cpu:
row resolution (copyPathToStore (./. + "/${sourcePath}")) os cpu null;
in
{
format = "bun2nix";
workspaces = [ "@example/shared" "bun-monorepo-example" "example-api" "example-web" ];
  packages = [
    (npm "hono" "4.9.8" "sha512-JW8Bb4RFWD9iOKxg5PbUarBYGM99IcxFl2FPBo2gSJO11jjUDqlP1Bmfyqt8Z/dGhIQ63PMA9LdcLefXyIasyg==" null null)
    (npm "kleur" "4.1.5" "sha512-o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==" null null)
    (npm "preact" "10.27.1" "sha512-V79raXEWch/rbqoNc7nT9E4ep7lu+mI3+sBmfRD4i1M73R3WLYcCtdI0ibxGVf4eQL8ZIz2nFacqEC+rmnOORQ==" null null)
  ];
  groups = {
    production = [
      [ [ 0 2 3 ] [ 1 ] ]
      [ [ 2 ] [ 0 ] ]
      [ [ 3 ] [ 2 ] ]
    ];
    check = [
      [ [ 0 2 3 ] [ 1 ] ]
      [ [ 2 ] [ 0 ] ]
      [ [ 2 3 ] [ 2 ] ]
    ];
    development = [
      [ [ 0 2 3 ] [ 1 ] ]
      [ [ 2 ] [ 0 ] ]
      [ [ 2 3 ] [ 2 ] ]
    ];
  };
}
