# Autogenerated by `bun2nix`; editing manually is not recommended
# Package sources and lock metadata for composable Bun cache derivations
{
copyPathToStore,
fetchFromGitHub,
fetchgit,
fetchurl,
...
}:
{
packages = {
    "@example/shared@workspace:packages/shared" = copyPathToStore (./. + "/packages/shared");
    "example-api@workspace:apps/api" = copyPathToStore (./. + "/apps/api");
    "example-web@workspace:apps/web" = copyPathToStore (./. + "/apps/web");
    "hono@4.9.8" = fetchurl {
      url = "https://registry.npmjs.org/hono/-/hono-4.9.8.tgz";
      hash = "sha512-JW8Bb4RFWD9iOKxg5PbUarBYGM99IcxFl2FPBo2gSJO11jjUDqlP1Bmfyqt8Z/dGhIQ63PMA9LdcLefXyIasyg==";
    };
    "kleur@4.1.5" = fetchurl {
      url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
      hash = "sha512-o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
    };
    "preact@10.27.1" = fetchurl {
      url = "https://registry.npmjs.org/preact/-/preact-10.27.1.tgz";
      hash = "sha512-V79raXEWch/rbqoNc7nT9E4ep7lu+mI3+sBmfRD4i1M73R3WLYcCtdI0ibxGVf4eQL8ZIz2nFacqEC+rmnOORQ==";
    };
  };
  metadata = {
    lockfileVersion = 2;
    workspacePackages = [ "@example/shared@workspace:packages/shared" "example-api@workspace:apps/api" "example-web@workspace:apps/web" ];
    productionDependencyClosures = {
      "@example/shared" = [ "kleur@4.1.5" ];
      "bun-monorepo-example" = [ ];
      "example-api" = [ "hono@4.9.8" "kleur@4.1.5" ];
      "example-web" = [ "kleur@4.1.5" "preact@10.27.1" ];
    };
    checkDependencyClosures = {
      "@example/shared" = [ "kleur@4.1.5" ];
      "bun-monorepo-example" = [ ];
      "example-api" = [ "hono@4.9.8" "kleur@4.1.5" "preact@10.27.1" ];
      "example-web" = [ "kleur@4.1.5" "preact@10.27.1" ];
    };
    developmentDependencyClosures = {
      "@example/shared" = [ "kleur@4.1.5" ];
      "bun-monorepo-example" = [ ];
      "example-api" = [ "hono@4.9.8" "kleur@4.1.5" "preact@10.27.1" ];
      "example-web" = [ "kleur@4.1.5" "preact@10.27.1" ];
    };
    packages = {
      "@example/shared@workspace:packages/shared" = {
        source = "workspace";
        local = true;
        os = null;
        cpu = null;
        registry = null;
      };
      "example-api@workspace:apps/api" = {
        source = "workspace";
        local = true;
        os = null;
        cpu = null;
        registry = null;
      };
      "example-web@workspace:apps/web" = {
        source = "workspace";
        local = true;
        os = null;
        cpu = null;
        registry = null;
      };
      "hono@4.9.8" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "kleur@4.1.5" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "preact@10.27.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
    };
  };
}
