[workspace]
resolver = "3"
members = [
  "crates/bun2nix",
  "crates/nix-tools",
  "crates/nix-tools-cache",
  "crates/nix-tools-core",
  "crates/nix-tools-engine",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT"
repository = "https://github.com/JacobDevelops/nix-tools"
publish = false

[workspace.dependencies]
askama = "0.14.0"
cap-fs-ext = "3.4.5"
cap-std = "3.4.5"
clap = { version = "4.5.47", features = ["derive"] }
itertools = "0.14.0"
jsonc-parser = { version = "0.26.3", features = ["serde"] }
nix = { version = "0.30.1", features = ["poll", "signal"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
signal-hook = "0.3.18"
thiserror = "2.0.16"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
