# Autogenerated by `bun2nix`; editing manually is not recommended
# Compact package and cache-group plan for Bun workspaces
/*nixfmt:disable*/
{
  fetchFromGitHub,
  fetchurl,
  ...
}:
let
  row = resolution: source: os: cpu: registry: [ resolution source os cpu registry ];
  npm = name: version: hash: os: cpu:
    row "${name}@${version}" (fetchurl {
      url = "https://registry.npmjs.org/${name}/-/${builtins.baseNameOf name}-${version}.tgz";
      inherit hash;
    }) os cpu null;
  github = resolution: owner: repo: rev: hash: os: cpu:
    row resolution (fetchFromGitHub { inherit owner repo rev hash; }) os cpu null;
  tarball = resolution: sourceUrl: hash: os: cpu:
    row resolution (builtins.fetchTarball { url = sourceUrl; sha256 = hash; }) os cpu null;
in
{
  format = "bun2nix";
  workspaces = [ "@corpus/app" "corpus-registry" ];
  packages = [
    (npm "@colors/colors" "1.6.0" "sha512-Ir+AOibqzrIsL6ajt3Rz3LskB7OiMVHqltZmspbW/TJuTVuyOMirVqAkjfY6JISiLHgyNqicAC8AyHHGzNd/dA==" null null)
    (npm "@esbuild/aix-ppc64" "0.25.9" "sha512-OaGtL73Jck6pBKjNIe24BnFE6agGl+6KxDtTfHhy1HmhthfKouEcOhqpSL64K4/0WCtbKFLOdzD/44cJ4k9opA==" [ "aix" ] [ "ppc64" ])
    (npm "@esbuild/android-arm64" "0.25.9" "sha512-IDrddSmpSv51ftWslJMvl3Q2ZT98fUSL2/rlUXuVqRXHCs5EUF1/f+jbjF5+NG9UffUDMCiTyh8iec7u8RlTLg==" [ "android" ] [ "arm64" ])
    (npm "@esbuild/android-arm" "0.25.9" "sha512-5WNI1DaMtxQ7t7B6xa572XMXpHAaI/9Hnhk8lcxF4zVN4xstUgTlvuGDorBguKEnZO70qwEcLpfifMLoxiPqHQ==" [ "android" ] [ "arm" ])
    (npm "@esbuild/android-x64" "0.25.9" "sha512-I853iMZ1hWZdNllhVZKm34f4wErd4lMyeV7BLzEExGEIZYsOzqDWDf+y082izYUE8gtJnYHdeDpN/6tUdwvfiw==" [ "android" ] [ "x64" ])
    (npm "@esbuild/darwin-arm64" "0.25.9" "sha512-XIpIDMAjOELi/9PB30vEbVMs3GV1v2zkkPnuyRRURbhqjyzIINwj+nbQATh4H9GxUgH1kFsEyQMxwiLFKUS6Rg==" [ "darwin" ] [ "arm64" ])
    (npm "@esbuild/darwin-x64" "0.25.9" "sha512-jhHfBzjYTA1IQu8VyrjCX4ApJDnH+ez+IYVEoJHeqJm9VhG9Dh2BYaJritkYK3vMaXrf7Ogr/0MQ8/MeIefsPQ==" [ "darwin" ] [ "x64" ])
    (npm "@esbuild/freebsd-arm64" "0.25.9" "sha512-z93DmbnY6fX9+KdD4Ue/H6sYs+bhFQJNCPZsi4XWJoYblUqT06MQUdBCpcSfuiN72AbqeBFu5LVQTjfXDE2A6Q==" [ "freebsd" ] [ "arm64" ])
    (npm "@esbuild/freebsd-x64" "0.25.9" "sha512-mrKX6H/vOyo5v71YfXWJxLVxgy1kyt1MQaD8wZJgJfG4gq4DpQGpgTB74e5yBeQdyMTbgxp0YtNj7NuHN0PoZg==" [ "freebsd" ] [ "x64" ])
    (npm "@esbuild/linux-arm64" "0.25.9" "sha512-BlB7bIcLT3G26urh5Dmse7fiLmLXnRlopw4s8DalgZ8ef79Jj4aUcYbk90g8iCa2467HX8SAIidbL7gsqXHdRw==" [ "linux" ] [ "arm64" ])
    (npm "@esbuild/linux-arm" "0.25.9" "sha512-HBU2Xv78SMgaydBmdor38lg8YDnFKSARg1Q6AT0/y2ezUAKiZvc211RDFHlEZRFNRVhcMamiToo7bDx3VEOYQw==" [ "linux" ] [ "arm" ])
    (npm "@esbuild/linux-ia32" "0.25.9" "sha512-e7S3MOJPZGp2QW6AK6+Ly81rC7oOSerQ+P8L0ta4FhVi+/j/v2yZzx5CqqDaWjtPFfYz21Vi1S0auHrap3Ma3A==" [ "linux" ] [ "ia32" ])
    (npm "@esbuild/linux-loong64" "0.25.9" "sha512-Sbe10Bnn0oUAB2AalYztvGcK+o6YFFA/9829PhOCUS9vkJElXGdphz0A3DbMdP8gmKkqPmPcMJmJOrI3VYB1JQ==" [ "linux" ] [ "loong64" ])
    (npm "@esbuild/linux-mips64el" "0.25.9" "sha512-YcM5br0mVyZw2jcQeLIkhWtKPeVfAerES5PvOzaDxVtIyZ2NUBZKNLjC5z3/fUlDgT6w89VsxP2qzNipOaaDyA==" [ "linux" ] [ "mips64el" ])
    (npm "@esbuild/linux-ppc64" "0.25.9" "sha512-++0HQvasdo20JytyDpFvQtNrEsAgNG2CY1CLMwGXfFTKGBGQT3bOeLSYE2l1fYdvML5KUuwn9Z8L1EWe2tzs1w==" [ "linux" ] [ "ppc64" ])
    (npm "@esbuild/linux-riscv64" "0.25.9" "sha512-uNIBa279Y3fkjV+2cUjx36xkx7eSjb8IvnL01eXUKXez/CBHNRw5ekCGMPM0BcmqBxBcdgUWuUXmVWwm4CH9kg==" [ "linux" ] [ "riscv64" ])
    (npm "@esbuild/linux-s390x" "0.25.9" "sha512-Mfiphvp3MjC/lctb+7D287Xw1DGzqJPb/J2aHHcHxflUo+8tmN/6d4k6I2yFR7BVo5/g7x2Monq4+Yew0EHRIA==" [ "linux" ] [ "s390x" ])
    (npm "@esbuild/linux-x64" "0.25.9" "sha512-iSwByxzRe48YVkmpbgoxVzn76BXjlYFXC7NvLYq+b+kDjyyk30J0JY47DIn8z1MO3K0oSl9fZoRmZPQI4Hklzg==" [ "linux" ] [ "x64" ])
    (npm "@esbuild/netbsd-arm64" "0.25.9" "sha512-9jNJl6FqaUG+COdQMjSCGW4QiMHH88xWbvZ+kRVblZsWrkXlABuGdFJ1E9L7HK+T0Yqd4akKNa/lO0+jDxQD4Q==" [ "netbsd" ] [ "arm64" ])
    (npm "@esbuild/netbsd-x64" "0.25.9" "sha512-RLLdkflmqRG8KanPGOU7Rpg829ZHu8nFy5Pqdi9U01VYtG9Y0zOG6Vr2z4/S+/3zIyOxiK6cCeYNWOFR9QP87g==" [ "netbsd" ] [ "x64" ])
    (npm "@esbuild/openbsd-arm64" "0.25.9" "sha512-YaFBlPGeDasft5IIM+CQAhJAqS3St3nJzDEgsgFixcfZeyGPCd6eJBWzke5piZuZ7CtL656eOSYKk4Ls2C0FRQ==" [ "openbsd" ] [ "arm64" ])
    (npm "@esbuild/openbsd-x64" "0.25.9" "sha512-1MkgTCuvMGWuqVtAvkpkXFmtL8XhWy+j4jaSO2wxfJtilVCi0ZE37b8uOdMItIHz4I6z1bWWtEX4CJwcKYLcuA==" [ "openbsd" ] [ "x64" ])
    (npm "@esbuild/openharmony-arm64" "0.25.9" "sha512-4Xd0xNiMVXKh6Fa7HEJQbrpP3m3DDn43jKxMjxLLRjWnRsfxjORYJlXPO4JNcXtOyfajXorRKY9NkOpTHptErg==" [ "openharmony" ] [ "arm64" ])
    (npm "@esbuild/sunos-x64" "0.25.9" "sha512-WjH4s6hzo00nNezhp3wFIAfmGZ8U7KtrJNlFMRKxiI9mxEK1scOMAaa9i4crUtu+tBr+0IN6JCuAcSBJZfnphw==" [ "sunos" ] [ "x64" ])
    (npm "@esbuild/win32-arm64" "0.25.9" "sha512-mGFrVJHmZiRqmP8xFOc6b84/7xa5y5YvR1x8djzXpJBSv/UsNK6aqec+6JDjConTgvvQefdGhFDAs2DLAds6gQ==" [ "win32" ] [ "arm64" ])
    (npm "@esbuild/win32-ia32" "0.25.9" "sha512-b33gLVU2k11nVx1OhX3C8QQP6UHQK4ZtN56oFWvVXvz2VkDoe6fbG8TOgHFxEvqeqohmRnIHe5A1+HADk4OQww==" [ "win32" ] [ "ia32" ])
    (npm "@esbuild/win32-x64" "0.25.9" "sha512-PPOl1mi6lpLNQxnGoyAfschAodRFYXJ+9fs6WHXz7CSWKbOqiMZsubC+BQsVKuul+3vKLuwTHsS2c2y9EoKwxQ==" [ "win32" ] [ "x64" ])
    (npm "@rollup/rollup-linux-x64-gnu" "4.46.2" "sha512-Jj5a9RUoe5ra+MEyERkDKLwTXVu6s3aACP51nkfnK9wJTraCC8IMe3snOfALkrjTYd2G1ViE1hICj0fZ7ALBPA==" [ "linux" ] [ "x64" ])
    (npm "call-bind-apply-helpers" "1.0.2" "sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==" null null)
    (npm "call-bound" "1.0.4" "sha512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==" null null)
    (npm "dunder-proto" "1.0.1" "sha512-KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==" null null)
    (npm "es-define-property" "1.0.1" "sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==" null null)
    (npm "es-errors" "1.3.0" "sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==" null null)
    (npm "es-object-atoms" "1.1.2" "sha512-HWcBoN6NileqtSydK2FqHbS/LoDd2pqrnQHLyJzBj4kOp/ky2MWMN694xOfkK8/SnUsW2DH7EfyVlydKCsm1Zw==" null null)
    (npm "esbuild" "0.25.9" "sha512-CRbODhYyQx3qp7ZEwzxOk4JBqmD/seJrzPa/cGjY1VtIn5E09Oi9/dB4JwctnfZ8Q8iT7rioVv5k/FNT/uf54g==" null null)
    (npm "fsevents" "2.3.3" "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==" [ "darwin" ] null)
    (npm "function-bind" "1.1.2" "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==" null null)
    (npm "get-intrinsic" "1.3.0" "sha512-9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==" null null)
    (npm "get-proto" "1.0.1" "sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==" null null)
    (npm "gopd" "1.2.0" "sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==" null null)
    (npm "has-symbols" "1.1.0" "sha512-1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==" null null)
    (npm "has-tostringtag" "1.0.2" "sha512-NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==" null null)
    (npm "hasown" "2.0.4" "sha512-T2UbfbBEF32wiepXIsMlTW9+dDYC6wMh/t/vYA4tuOMKqWz/n3vr1NFSxQiyP+zk2mXsoMA/i/7qV6LKut1t1A==" null null)
    (npm "is-even" "1.0.0" "sha512-LEhnkAdJqic4Dbqn58A0y52IXoHWlsueqQkKfMfdEnIYG8A1sm/GHidKkS6yvXlMoRrkM34csHnXQtOqcb+Jzg==" null null)
    (github "is-number-object@github:inspect-js/is-number-object#5181bb2" "inspect-js" "is-number-object" "5181bb2" "sha256-AeeZP8lKYvMohCBPRHYkB/tFW7ZXZrcOn/aD7SJmWws=" null null)
    (npm "is-number" "7.0.0" "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==" null null)
    (npm "is-odd" "0.1.2" "sha512-Ri7C2K7o5IrUU9UEI8losXJCCD/UtsaIrkR5sxIcFg4xQ9cRJXlWA5DQvTE0yDc0krvSNLsRGXN11UPS6KyfBw==" null null)
    (npm "is-odd" "3.0.1" "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==" null null)
    (npm "kleur" "4.1.5" "sha512-o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==" null null)
    (tarball "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "sha256-GfBnO6v505JHnsIcZv5iA+DxVSVnUHYAk/fX/eKR6u8=" null null)
    (npm "math-intrinsics" "1.1.0" "sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==" null null)
    (npm "react" "19.1.1" "sha512-w8nqGImo45dmMIfljjMwOGtbmC/mk4CMYhWIicdSflH91J9TyCyczcPFXJzrZ/ZXcgGRFeP6BU0BEJTw6tZdfQ==" null null)
  ];
  groups = {
    production = [
      [ [ 0 ] [ 47 48 ] ]
      [ [ 0 1 ] [ 45 ] ]
      [ [ 1 ] [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 44 49 50 51 ] ]
    ];
    check = [
      [ [ 0 ] [ 43 46 47 48 ] ]
      [ [ 0 1 ] [ 45 ] ]
      [ [ 1 ] [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 44 49 50 51 ] ]
    ];
    development = [
      [ [ 0 ] [ 43 46 47 48 ] ]
      [ [ 0 1 ] [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 44 45 49 50 51 ] ]
    ];
  };
}
