# Autogenerated by `bun2nix`; editing manually is not recommended
# Package sources and lock metadata for composable Bun cache derivations
{
copyPathToStore,
fetchFromGitHub,
fetchgit,
fetchurl,
...
}:
{
packages = {
    "@colors/colors@1.6.0" = fetchurl {
      url = "https://registry.npmjs.org/@colors/colors/-/colors-1.6.0.tgz";
      hash = "sha512-Ir+AOibqzrIsL6ajt3Rz3LskB7OiMVHqltZmspbW/TJuTVuyOMirVqAkjfY6JISiLHgyNqicAC8AyHHGzNd/dA==";
    };
    "@corpus/app@workspace:packages/app" = copyPathToStore (./. + "/packages/app");
    "@esbuild/aix-ppc64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/aix-ppc64/-/aix-ppc64-0.25.9.tgz";
      hash = "sha512-OaGtL73Jck6pBKjNIe24BnFE6agGl+6KxDtTfHhy1HmhthfKouEcOhqpSL64K4/0WCtbKFLOdzD/44cJ4k9opA==";
    };
    "@esbuild/android-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/android-arm64/-/android-arm64-0.25.9.tgz";
      hash = "sha512-IDrddSmpSv51ftWslJMvl3Q2ZT98fUSL2/rlUXuVqRXHCs5EUF1/f+jbjF5+NG9UffUDMCiTyh8iec7u8RlTLg==";
    };
    "@esbuild/android-arm@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/android-arm/-/android-arm-0.25.9.tgz";
      hash = "sha512-5WNI1DaMtxQ7t7B6xa572XMXpHAaI/9Hnhk8lcxF4zVN4xstUgTlvuGDorBguKEnZO70qwEcLpfifMLoxiPqHQ==";
    };
    "@esbuild/android-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/android-x64/-/android-x64-0.25.9.tgz";
      hash = "sha512-I853iMZ1hWZdNllhVZKm34f4wErd4lMyeV7BLzEExGEIZYsOzqDWDf+y082izYUE8gtJnYHdeDpN/6tUdwvfiw==";
    };
    "@esbuild/darwin-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.25.9.tgz";
      hash = "sha512-XIpIDMAjOELi/9PB30vEbVMs3GV1v2zkkPnuyRRURbhqjyzIINwj+nbQATh4H9GxUgH1kFsEyQMxwiLFKUS6Rg==";
    };
    "@esbuild/darwin-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/darwin-x64/-/darwin-x64-0.25.9.tgz";
      hash = "sha512-jhHfBzjYTA1IQu8VyrjCX4ApJDnH+ez+IYVEoJHeqJm9VhG9Dh2BYaJritkYK3vMaXrf7Ogr/0MQ8/MeIefsPQ==";
    };
    "@esbuild/freebsd-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/freebsd-arm64/-/freebsd-arm64-0.25.9.tgz";
      hash = "sha512-z93DmbnY6fX9+KdD4Ue/H6sYs+bhFQJNCPZsi4XWJoYblUqT06MQUdBCpcSfuiN72AbqeBFu5LVQTjfXDE2A6Q==";
    };
    "@esbuild/freebsd-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/freebsd-x64/-/freebsd-x64-0.25.9.tgz";
      hash = "sha512-mrKX6H/vOyo5v71YfXWJxLVxgy1kyt1MQaD8wZJgJfG4gq4DpQGpgTB74e5yBeQdyMTbgxp0YtNj7NuHN0PoZg==";
    };
    "@esbuild/linux-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-0.25.9.tgz";
      hash = "sha512-BlB7bIcLT3G26urh5Dmse7fiLmLXnRlopw4s8DalgZ8ef79Jj4aUcYbk90g8iCa2467HX8SAIidbL7gsqXHdRw==";
    };
    "@esbuild/linux-arm@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-arm/-/linux-arm-0.25.9.tgz";
      hash = "sha512-HBU2Xv78SMgaydBmdor38lg8YDnFKSARg1Q6AT0/y2ezUAKiZvc211RDFHlEZRFNRVhcMamiToo7bDx3VEOYQw==";
    };
    "@esbuild/linux-ia32@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-ia32/-/linux-ia32-0.25.9.tgz";
      hash = "sha512-e7S3MOJPZGp2QW6AK6+Ly81rC7oOSerQ+P8L0ta4FhVi+/j/v2yZzx5CqqDaWjtPFfYz21Vi1S0auHrap3Ma3A==";
    };
    "@esbuild/linux-loong64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-loong64/-/linux-loong64-0.25.9.tgz";
      hash = "sha512-Sbe10Bnn0oUAB2AalYztvGcK+o6YFFA/9829PhOCUS9vkJElXGdphz0A3DbMdP8gmKkqPmPcMJmJOrI3VYB1JQ==";
    };
    "@esbuild/linux-mips64el@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-mips64el/-/linux-mips64el-0.25.9.tgz";
      hash = "sha512-YcM5br0mVyZw2jcQeLIkhWtKPeVfAerES5PvOzaDxVtIyZ2NUBZKNLjC5z3/fUlDgT6w89VsxP2qzNipOaaDyA==";
    };
    "@esbuild/linux-ppc64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-ppc64/-/linux-ppc64-0.25.9.tgz";
      hash = "sha512-++0HQvasdo20JytyDpFvQtNrEsAgNG2CY1CLMwGXfFTKGBGQT3bOeLSYE2l1fYdvML5KUuwn9Z8L1EWe2tzs1w==";
    };
    "@esbuild/linux-riscv64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-riscv64/-/linux-riscv64-0.25.9.tgz";
      hash = "sha512-uNIBa279Y3fkjV+2cUjx36xkx7eSjb8IvnL01eXUKXez/CBHNRw5ekCGMPM0BcmqBxBcdgUWuUXmVWwm4CH9kg==";
    };
    "@esbuild/linux-s390x@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-s390x/-/linux-s390x-0.25.9.tgz";
      hash = "sha512-Mfiphvp3MjC/lctb+7D287Xw1DGzqJPb/J2aHHcHxflUo+8tmN/6d4k6I2yFR7BVo5/g7x2Monq4+Yew0EHRIA==";
    };
    "@esbuild/linux-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.25.9.tgz";
      hash = "sha512-iSwByxzRe48YVkmpbgoxVzn76BXjlYFXC7NvLYq+b+kDjyyk30J0JY47DIn8z1MO3K0oSl9fZoRmZPQI4Hklzg==";
    };
    "@esbuild/netbsd-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/netbsd-arm64/-/netbsd-arm64-0.25.9.tgz";
      hash = "sha512-9jNJl6FqaUG+COdQMjSCGW4QiMHH88xWbvZ+kRVblZsWrkXlABuGdFJ1E9L7HK+T0Yqd4akKNa/lO0+jDxQD4Q==";
    };
    "@esbuild/netbsd-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/netbsd-x64/-/netbsd-x64-0.25.9.tgz";
      hash = "sha512-RLLdkflmqRG8KanPGOU7Rpg829ZHu8nFy5Pqdi9U01VYtG9Y0zOG6Vr2z4/S+/3zIyOxiK6cCeYNWOFR9QP87g==";
    };
    "@esbuild/openbsd-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/openbsd-arm64/-/openbsd-arm64-0.25.9.tgz";
      hash = "sha512-YaFBlPGeDasft5IIM+CQAhJAqS3St3nJzDEgsgFixcfZeyGPCd6eJBWzke5piZuZ7CtL656eOSYKk4Ls2C0FRQ==";
    };
    "@esbuild/openbsd-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/openbsd-x64/-/openbsd-x64-0.25.9.tgz";
      hash = "sha512-1MkgTCuvMGWuqVtAvkpkXFmtL8XhWy+j4jaSO2wxfJtilVCi0ZE37b8uOdMItIHz4I6z1bWWtEX4CJwcKYLcuA==";
    };
    "@esbuild/openharmony-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/openharmony-arm64/-/openharmony-arm64-0.25.9.tgz";
      hash = "sha512-4Xd0xNiMVXKh6Fa7HEJQbrpP3m3DDn43jKxMjxLLRjWnRsfxjORYJlXPO4JNcXtOyfajXorRKY9NkOpTHptErg==";
    };
    "@esbuild/sunos-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/sunos-x64/-/sunos-x64-0.25.9.tgz";
      hash = "sha512-WjH4s6hzo00nNezhp3wFIAfmGZ8U7KtrJNlFMRKxiI9mxEK1scOMAaa9i4crUtu+tBr+0IN6JCuAcSBJZfnphw==";
    };
    "@esbuild/win32-arm64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/win32-arm64/-/win32-arm64-0.25.9.tgz";
      hash = "sha512-mGFrVJHmZiRqmP8xFOc6b84/7xa5y5YvR1x8djzXpJBSv/UsNK6aqec+6JDjConTgvvQefdGhFDAs2DLAds6gQ==";
    };
    "@esbuild/win32-ia32@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/win32-ia32/-/win32-ia32-0.25.9.tgz";
      hash = "sha512-b33gLVU2k11nVx1OhX3C8QQP6UHQK4ZtN56oFWvVXvz2VkDoe6fbG8TOgHFxEvqeqohmRnIHe5A1+HADk4OQww==";
    };
    "@esbuild/win32-x64@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/win32-x64/-/win32-x64-0.25.9.tgz";
      hash = "sha512-PPOl1mi6lpLNQxnGoyAfschAodRFYXJ+9fs6WHXz7CSWKbOqiMZsubC+BQsVKuul+3vKLuwTHsS2c2y9EoKwxQ==";
    };
    "@rollup/rollup-linux-x64-gnu@4.46.2" = fetchurl {
      url = "https://registry.npmjs.org/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.46.2.tgz";
      hash = "sha512-Jj5a9RUoe5ra+MEyERkDKLwTXVu6s3aACP51nkfnK9wJTraCC8IMe3snOfALkrjTYd2G1ViE1hICj0fZ7ALBPA==";
    };
    "call-bind-apply-helpers@1.0.2" = fetchurl {
      url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
      hash = "sha512-Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
    };
    "call-bound@1.0.4" = fetchurl {
      url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
      hash = "sha512-+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
    };
    "dunder-proto@1.0.1" = fetchurl {
      url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
      hash = "sha512-KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
    };
    "es-define-property@1.0.1" = fetchurl {
      url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
      hash = "sha512-e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
    };
    "es-errors@1.3.0" = fetchurl {
      url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
      hash = "sha512-Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
    };
    "es-object-atoms@1.1.2" = fetchurl {
      url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.2.tgz";
      hash = "sha512-HWcBoN6NileqtSydK2FqHbS/LoDd2pqrnQHLyJzBj4kOp/ky2MWMN694xOfkK8/SnUsW2DH7EfyVlydKCsm1Zw==";
    };
    "esbuild@0.25.9" = fetchurl {
      url = "https://registry.npmjs.org/esbuild/-/esbuild-0.25.9.tgz";
      hash = "sha512-CRbODhYyQx3qp7ZEwzxOk4JBqmD/seJrzPa/cGjY1VtIn5E09Oi9/dB4JwctnfZ8Q8iT7rioVv5k/FNT/uf54g==";
    };
    "fsevents@2.3.3" = fetchurl {
      url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.3.tgz";
      hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
    };
    "function-bind@1.1.2" = fetchurl {
      url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
      hash = "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
    };
    "get-intrinsic@1.3.0" = fetchurl {
      url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz";
      hash = "sha512-9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==";
    };
    "get-proto@1.0.1" = fetchurl {
      url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
      hash = "sha512-sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
    };
    "gopd@1.2.0" = fetchurl {
      url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
      hash = "sha512-ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
    };
    "has-symbols@1.1.0" = fetchurl {
      url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
      hash = "sha512-1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
    };
    "has-tostringtag@1.0.2" = fetchurl {
      url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
      hash = "sha512-NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
    };
    "hasown@2.0.4" = fetchurl {
      url = "https://registry.npmjs.org/hasown/-/hasown-2.0.4.tgz";
      hash = "sha512-T2UbfbBEF32wiepXIsMlTW9+dDYC6wMh/t/vYA4tuOMKqWz/n3vr1NFSxQiyP+zk2mXsoMA/i/7qV6LKut1t1A==";
    };
    "is-even@1.0.0" = fetchurl {
      url = "https://registry.npmjs.org/is-even/-/is-even-1.0.0.tgz";
      hash = "sha512-LEhnkAdJqic4Dbqn58A0y52IXoHWlsueqQkKfMfdEnIYG8A1sm/GHidKkS6yvXlMoRrkM34csHnXQtOqcb+Jzg==";
    };
    "is-number-object@github:inspect-js/is-number-object#5181bb2" = fetchFromGitHub {
      owner = "inspect-js";
      repo = "is-number-object";
      rev = "5181bb2";
      hash = "sha256-AeeZP8lKYvMohCBPRHYkB/tFW7ZXZrcOn/aD7SJmWws=";
    };
    "is-number@7.0.0" = fetchurl {
      url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
      hash = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
    };
    "is-odd@0.1.2" = fetchurl {
      url = "https://registry.npmjs.org/is-odd/-/is-odd-0.1.2.tgz";
      hash = "sha512-Ri7C2K7o5IrUU9UEI8losXJCCD/UtsaIrkR5sxIcFg4xQ9cRJXlWA5DQvTE0yDc0krvSNLsRGXN11UPS6KyfBw==";
    };
    "is-odd@3.0.1" = fetchurl {
      url = "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz";
      hash = "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==";
    };
    "kleur@4.1.5" = fetchurl {
      url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
      hash = "sha512-o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==";
    };
    "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" = builtins.fetchTarball {
      url = "https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz";
      sha256 = "sha256-GfBnO6v505JHnsIcZv5iA+DxVSVnUHYAk/fX/eKR6u8=";
    };
    "math-intrinsics@1.1.0" = fetchurl {
      url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
      hash = "sha512-/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
    };
    "react@19.1.1" = fetchurl {
      url = "https://registry.npmjs.org/react/-/react-19.1.1.tgz";
      hash = "sha512-w8nqGImo45dmMIfljjMwOGtbmC/mk4CMYhWIicdSflH91J9TyCyczcPFXJzrZ/ZXcgGRFeP6BU0BEJTw6tZdfQ==";
    };
  };
  metadata = {
    lockfileVersion = 2;
    workspacePackages = [ "@corpus/app@workspace:packages/app" ];
    productionDependencyClosures = {
      "@corpus/app" = [ "is-number@7.0.0" "is-odd@3.0.1" "kleur@4.1.5" ];
      "corpus-registry" = [ "@colors/colors@1.6.0" "@esbuild/aix-ppc64@0.25.9" "@esbuild/android-arm64@0.25.9" "@esbuild/android-arm@0.25.9" "@esbuild/android-x64@0.25.9" "@esbuild/darwin-arm64@0.25.9" "@esbuild/darwin-x64@0.25.9" "@esbuild/freebsd-arm64@0.25.9" "@esbuild/freebsd-x64@0.25.9" "@esbuild/linux-arm64@0.25.9" "@esbuild/linux-arm@0.25.9" "@esbuild/linux-ia32@0.25.9" "@esbuild/linux-loong64@0.25.9" "@esbuild/linux-mips64el@0.25.9" "@esbuild/linux-ppc64@0.25.9" "@esbuild/linux-riscv64@0.25.9" "@esbuild/linux-s390x@0.25.9" "@esbuild/linux-x64@0.25.9" "@esbuild/netbsd-arm64@0.25.9" "@esbuild/netbsd-x64@0.25.9" "@esbuild/openbsd-arm64@0.25.9" "@esbuild/openbsd-x64@0.25.9" "@esbuild/openharmony-arm64@0.25.9" "@esbuild/sunos-x64@0.25.9" "@esbuild/win32-arm64@0.25.9" "@esbuild/win32-ia32@0.25.9" "@esbuild/win32-x64@0.25.9" "@rollup/rollup-linux-x64-gnu@4.46.2" "call-bind-apply-helpers@1.0.2" "call-bound@1.0.4" "dunder-proto@1.0.1" "es-define-property@1.0.1" "es-errors@1.3.0" "es-object-atoms@1.1.2" "esbuild@0.25.9" "fsevents@2.3.3" "function-bind@1.1.2" "get-intrinsic@1.3.0" "get-proto@1.0.1" "gopd@1.2.0" "has-symbols@1.1.0" "has-tostringtag@1.0.2" "hasown@2.0.4" "is-number-object@github:inspect-js/is-number-object#5181bb2" "is-number@7.0.0" "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "math-intrinsics@1.1.0" "react@19.1.1" ];
    };
    checkDependencyClosures = {
      "@corpus/app" = [ "is-even@1.0.0" "is-number@7.0.0" "is-odd@0.1.2" "is-odd@3.0.1" "kleur@4.1.5" ];
      "corpus-registry" = [ "@colors/colors@1.6.0" "@esbuild/aix-ppc64@0.25.9" "@esbuild/android-arm64@0.25.9" "@esbuild/android-arm@0.25.9" "@esbuild/android-x64@0.25.9" "@esbuild/darwin-arm64@0.25.9" "@esbuild/darwin-x64@0.25.9" "@esbuild/freebsd-arm64@0.25.9" "@esbuild/freebsd-x64@0.25.9" "@esbuild/linux-arm64@0.25.9" "@esbuild/linux-arm@0.25.9" "@esbuild/linux-ia32@0.25.9" "@esbuild/linux-loong64@0.25.9" "@esbuild/linux-mips64el@0.25.9" "@esbuild/linux-ppc64@0.25.9" "@esbuild/linux-riscv64@0.25.9" "@esbuild/linux-s390x@0.25.9" "@esbuild/linux-x64@0.25.9" "@esbuild/netbsd-arm64@0.25.9" "@esbuild/netbsd-x64@0.25.9" "@esbuild/openbsd-arm64@0.25.9" "@esbuild/openbsd-x64@0.25.9" "@esbuild/openharmony-arm64@0.25.9" "@esbuild/sunos-x64@0.25.9" "@esbuild/win32-arm64@0.25.9" "@esbuild/win32-ia32@0.25.9" "@esbuild/win32-x64@0.25.9" "@rollup/rollup-linux-x64-gnu@4.46.2" "call-bind-apply-helpers@1.0.2" "call-bound@1.0.4" "dunder-proto@1.0.1" "es-define-property@1.0.1" "es-errors@1.3.0" "es-object-atoms@1.1.2" "esbuild@0.25.9" "fsevents@2.3.3" "function-bind@1.1.2" "get-intrinsic@1.3.0" "get-proto@1.0.1" "gopd@1.2.0" "has-symbols@1.1.0" "has-tostringtag@1.0.2" "hasown@2.0.4" "is-number-object@github:inspect-js/is-number-object#5181bb2" "is-number@7.0.0" "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "math-intrinsics@1.1.0" "react@19.1.1" ];
    };
    developmentDependencyClosures = {
      "@corpus/app" = [ "@colors/colors@1.6.0" "@esbuild/aix-ppc64@0.25.9" "@esbuild/android-arm64@0.25.9" "@esbuild/android-arm@0.25.9" "@esbuild/android-x64@0.25.9" "@esbuild/darwin-arm64@0.25.9" "@esbuild/darwin-x64@0.25.9" "@esbuild/freebsd-arm64@0.25.9" "@esbuild/freebsd-x64@0.25.9" "@esbuild/linux-arm64@0.25.9" "@esbuild/linux-arm@0.25.9" "@esbuild/linux-ia32@0.25.9" "@esbuild/linux-loong64@0.25.9" "@esbuild/linux-mips64el@0.25.9" "@esbuild/linux-ppc64@0.25.9" "@esbuild/linux-riscv64@0.25.9" "@esbuild/linux-s390x@0.25.9" "@esbuild/linux-x64@0.25.9" "@esbuild/netbsd-arm64@0.25.9" "@esbuild/netbsd-x64@0.25.9" "@esbuild/openbsd-arm64@0.25.9" "@esbuild/openbsd-x64@0.25.9" "@esbuild/openharmony-arm64@0.25.9" "@esbuild/sunos-x64@0.25.9" "@esbuild/win32-arm64@0.25.9" "@esbuild/win32-ia32@0.25.9" "@esbuild/win32-x64@0.25.9" "@rollup/rollup-linux-x64-gnu@4.46.2" "call-bind-apply-helpers@1.0.2" "call-bound@1.0.4" "dunder-proto@1.0.1" "es-define-property@1.0.1" "es-errors@1.3.0" "es-object-atoms@1.1.2" "esbuild@0.25.9" "fsevents@2.3.3" "function-bind@1.1.2" "get-intrinsic@1.3.0" "get-proto@1.0.1" "gopd@1.2.0" "has-symbols@1.1.0" "has-tostringtag@1.0.2" "hasown@2.0.4" "is-even@1.0.0" "is-number-object@github:inspect-js/is-number-object#5181bb2" "is-number@7.0.0" "is-odd@0.1.2" "is-odd@3.0.1" "kleur@4.1.5" "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "math-intrinsics@1.1.0" "react@19.1.1" ];
      "corpus-registry" = [ "@colors/colors@1.6.0" "@esbuild/aix-ppc64@0.25.9" "@esbuild/android-arm64@0.25.9" "@esbuild/android-arm@0.25.9" "@esbuild/android-x64@0.25.9" "@esbuild/darwin-arm64@0.25.9" "@esbuild/darwin-x64@0.25.9" "@esbuild/freebsd-arm64@0.25.9" "@esbuild/freebsd-x64@0.25.9" "@esbuild/linux-arm64@0.25.9" "@esbuild/linux-arm@0.25.9" "@esbuild/linux-ia32@0.25.9" "@esbuild/linux-loong64@0.25.9" "@esbuild/linux-mips64el@0.25.9" "@esbuild/linux-ppc64@0.25.9" "@esbuild/linux-riscv64@0.25.9" "@esbuild/linux-s390x@0.25.9" "@esbuild/linux-x64@0.25.9" "@esbuild/netbsd-arm64@0.25.9" "@esbuild/netbsd-x64@0.25.9" "@esbuild/openbsd-arm64@0.25.9" "@esbuild/openbsd-x64@0.25.9" "@esbuild/openharmony-arm64@0.25.9" "@esbuild/sunos-x64@0.25.9" "@esbuild/win32-arm64@0.25.9" "@esbuild/win32-ia32@0.25.9" "@esbuild/win32-x64@0.25.9" "@rollup/rollup-linux-x64-gnu@4.46.2" "call-bind-apply-helpers@1.0.2" "call-bound@1.0.4" "dunder-proto@1.0.1" "es-define-property@1.0.1" "es-errors@1.3.0" "es-object-atoms@1.1.2" "esbuild@0.25.9" "fsevents@2.3.3" "function-bind@1.1.2" "get-intrinsic@1.3.0" "get-proto@1.0.1" "gopd@1.2.0" "has-symbols@1.1.0" "has-tostringtag@1.0.2" "hasown@2.0.4" "is-number-object@github:inspect-js/is-number-object#5181bb2" "is-number@7.0.0" "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" "math-intrinsics@1.1.0" "react@19.1.1" ];
    };
    packages = {
      "@colors/colors@1.6.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "@corpus/app@workspace:packages/app" = {
        source = "workspace";
        local = true;
        os = null;
        cpu = null;
        registry = null;
      };
      "@esbuild/aix-ppc64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "aix" ];
        cpu = [ "ppc64" ];
        registry = null;
      };
      "@esbuild/android-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "android" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/android-arm@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "android" ];
        cpu = [ "arm" ];
        registry = null;
      };
      "@esbuild/android-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "android" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/darwin-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "darwin" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/darwin-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "darwin" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/freebsd-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "freebsd" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/freebsd-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "freebsd" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/linux-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/linux-arm@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "arm" ];
        registry = null;
      };
      "@esbuild/linux-ia32@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "ia32" ];
        registry = null;
      };
      "@esbuild/linux-loong64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "none" ];
        registry = null;
      };
      "@esbuild/linux-mips64el@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "none" ];
        registry = null;
      };
      "@esbuild/linux-ppc64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "ppc64" ];
        registry = null;
      };
      "@esbuild/linux-riscv64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "none" ];
        registry = null;
      };
      "@esbuild/linux-s390x@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "s390x" ];
        registry = null;
      };
      "@esbuild/linux-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/netbsd-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "none" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/netbsd-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "none" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/openbsd-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "openbsd" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/openbsd-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "openbsd" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/openharmony-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "none" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/sunos-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "sunos" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@esbuild/win32-arm64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "win32" ];
        cpu = [ "arm64" ];
        registry = null;
      };
      "@esbuild/win32-ia32@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "win32" ];
        cpu = [ "ia32" ];
        registry = null;
      };
      "@esbuild/win32-x64@0.25.9" = {
        source = "npm";
        local = false;
        os = [ "win32" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "@rollup/rollup-linux-x64-gnu@4.46.2" = {
        source = "npm";
        local = false;
        os = [ "linux" ];
        cpu = [ "x64" ];
        registry = null;
      };
      "call-bind-apply-helpers@1.0.2" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "call-bound@1.0.4" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "dunder-proto@1.0.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "es-define-property@1.0.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "es-errors@1.3.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "es-object-atoms@1.1.2" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "esbuild@0.25.9" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "fsevents@2.3.3" = {
        source = "npm";
        local = false;
        os = [ "darwin" ];
        cpu = null;
        registry = null;
      };
      "function-bind@1.1.2" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "get-intrinsic@1.3.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "get-proto@1.0.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "gopd@1.2.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "has-symbols@1.1.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "has-tostringtag@1.0.2" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "hasown@2.0.4" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "is-even@1.0.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "is-number-object@github:inspect-js/is-number-object#5181bb2" = {
        source = "github";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "is-number@7.0.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "is-odd@0.1.2" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "is-odd@3.0.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "kleur@4.1.5" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "kleur@https://registry.npmjs.org/kleur/-/kleur-4.1.5.tgz" = {
        source = "tarball";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "math-intrinsics@1.1.0" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
      "react@19.1.1" = {
        source = "npm";
        local = false;
        os = null;
        cpu = null;
        registry = null;
      };
    };
  };
}
