//! Integration tests for deterministic `bun.nix` conversion.

use std::sync::Mutex;

use bun2nix::{
    ConvertOptions, Error, Lockfile, Prefetcher, Result, convert_lockfile_with_prefetcher,
};

struct NoPrefetch;

impl Prefetcher for NoPrefetch {
    fn prefetch(&self, source: &str) -> Result<String> {
        panic!("unexpected prefetch for {source}")
    }
}

#[derive(Default)]
struct RecordingPrefetcher {
    sources: Mutex<Vec<String>>,
}

impl Prefetcher for RecordingPrefetcher {
    fn prefetch(&self, source: &str) -> Result<String> {
        self.sources.lock().unwrap().push(source.to_owned());
        Ok("sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".to_owned())
    }
}

fn lockfile(version: u8) -> String {
    format!(
        r#"{{
          "lockfileVersion": {version},
          "workspaces": {{
            "": {{ "name": "root", "devDependencies": {{ "root-only": "1" }} }},
            "apps/web": {{
              "name": "web",
              "dependencies": {{ "native": "1", "shared": "1" }},
              "devDependencies": {{ "tool": "1" }}
            }}
          }},
          "packages": {{
            "native": ["native@2.0.0", "", {{ "os": "linux", "cpu": ["x64", "arm64"] }}, "sha512-native"],
            "root-only": ["root-only@1.0.0", "", {{}}, "sha512-root"],
            "shared": ["shared@1.0.0", "", {{}}, "sha512-shared"],
            "tool": ["tool@3.0.0", "https://npm.example.test/tool/-/tool-3.0.0.tgz", {{}}, "sha512-tool"],
            "web": ["web@workspace:apps/web"]
          }}
        }}"#
    )
}

#[test]
fn renders_compact_package_and_group_plan() {
    let output =
        convert_lockfile_with_prefetcher(&lockfile(3), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();

    assert!(output.starts_with("# Autogenerated by `bun2nix`"));
    assert!(output.contains("format = \"bun2nix\";"));
    assert!(output.contains("workspaces = [ \"root\" \"web\" ];"));
    assert!(output.contains(
        "(npm \"native\" \"2.0.0\" \"sha512-native\" [ \"linux\" ] [ \"arm64\" \"x64\" ])"
    ));
    assert!(output.contains(
        "(url \"tool@3.0.0\" \"https://npm.example.test/tool/-/tool-3.0.0.tgz\" \"tool-3.0.0.tgz\" \"sha512-tool\" null null \"npm.example.test\")"
    ));
    assert!(!output.contains("web@workspace:apps/web"));
    assert!(output.contains("production = [\n      [ [ 1 ] [ 0 2 ] ]\n    ];"));
    assert!(output.contains("check = [\n      [ [ 0 ] [ 1 ] ]\n      [ [ 1 ] [ 0 2 3 ] ]\n    ];"));
    assert!(
        output.contains(
            "development = [\n      [ [ 0 1 ] [ 1 ] ]\n      [ [ 1 ] [ 0 2 3 ] ]\n    ];"
        )
    );
}

#[test]
fn lockfile_versions_render_identically() {
    let version_one =
        convert_lockfile_with_prefetcher(&lockfile(1), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();
    let version_three =
        convert_lockfile_with_prefetcher(&lockfile(3), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();

    assert_eq!(version_one, version_three);
}

#[test]
fn prefetches_direct_tarball_git_and_github_sources() {
    let lock = r#"{
      "lockfileVersion": 1,
      "workspaces": {},
      "packages": {
        "tar": ["tar@https://example.test/tar.tgz", {}],
        "git": ["git@git+https://git.example.test/repo.git#deadbeef", {}, "deadbeef"],
        "git-ssh": ["git-ssh@git+ssh://git@git.example.test/repo.git#facefeed", {}, "facefeed"],
        "github": ["github@github:owner/repo#cafebabe", {}, "owner-repo-cafebabe"]
      }
    }"#;
    let prefetcher = RecordingPrefetcher::default();

    let output =
        convert_lockfile_with_prefetcher(lock, &ConvertOptions::default(), &prefetcher).unwrap();

    let hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    assert!(output.contains(&format!(
        "(tarball \"tar@https://example.test/tar.tgz\" \"https://example.test/tar.tgz\" \"{hash}\" null null)"
    )));
    assert!(output.contains(&format!(
        "(git \"git@git+https://git.example.test/repo.git#deadbeef\" \"https://git.example.test/repo.git\" \"deadbeef\" \"{hash}\" null null)"
    )));
    assert!(output.contains(&format!(
        "(git \"git-ssh@git+ssh://git@git.example.test/repo.git#facefeed\" \"ssh://git@git.example.test/repo.git\" \"facefeed\" \"{hash}\" null null)"
    )));
    assert!(output.contains(&format!(
        "(github \"github@github:owner/repo#cafebabe\" \"owner\" \"repo\" \"cafebabe\" \"{hash}\" null null)"
    )));
    assert_eq!(
        *prefetcher.sources.lock().unwrap(),
        [
            "git+https://git.example.test/repo.git?rev=deadbeef",
            "git+ssh://git@git.example.test/repo.git?rev=facefeed",
            "https://github.com/owner/repo/archive/cafebabe.tar.gz",
            "https://example.test/tar.tgz",
        ]
    );
}

#[test]
fn parsed_lockfile_closures_are_stable_across_repeated_calls() {
    let lock = Lockfile::parse(&lockfile(3)).unwrap();
    assert_eq!(
        lock.dependency_closures().unwrap(),
        lock.dependency_closures().unwrap()
    );
}

#[test]
fn rejects_local_lockfile_paths_that_escape_the_source_root() {
    let result = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 1,
          "workspaces": {},
          "packages": { "escape": ["escape@file:../outside"] }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    );

    assert!(matches!(result, Err(Error::InvalidPackage { key, .. }) if key == "escape"));
}

#[test]
fn renders_workspace_relative_path_tarballs_as_cacheable_local_sources() {
    let output = convert_lockfile_with_prefetcher(
        include_str!("fixtures/path-local-tarball.lock"),
        &ConvertOptions::default(),
        &NoPrefetch,
    )
    .unwrap();

    assert!(output.contains(
        "(path \"tar-local@../../vendor/tar-local.tgz\" \"vendor/tar-local.tgz\" null null)"
    ));
    assert!(!output.contains("app@workspace:apps/app"));
    assert!(output.contains("production = [\n      [ [ 0 ] [ 0 1 ] ]\n    ];"));
}

#[test]
fn rejects_workspace_relative_tarballs_that_escape_the_repository() {
    let lockfile = include_str!("fixtures/path-local-tarball.lock")
        .replace("../../vendor/tar-local.tgz", "../../../outside.tgz");

    let result =
        convert_lockfile_with_prefetcher(&lockfile, &ConvertOptions::default(), &NoPrefetch);

    assert!(matches!(result, Err(Error::InvalidPackage { key, .. }) if key == "tar-local"));
}

#[test]
fn uses_buns_hostname_only_private_registry_cache_identity() {
    let output = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 3,
          "workspaces": { "": { "name": "app", "dependencies": { "private": "1" } } },
          "packages": {
            "private": [
              "private@1.0.0",
              "http://127.0.0.1:4873/npm/private/-/private-1.0.0.tgz",
              {},
              "sha512-private"
            ]
          }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    )
    .unwrap();

    assert!(output.contains("null null \"127.0.0.1\")"));
    assert!(!output.contains("registry = \"127.0.0.1:4873\";"));
}

#[test]
fn rejects_long_private_registry_hosts_that_need_unrecorded_registry_url_hashing() {
    let result = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 3,
          "workspaces": { "": { "name": "app", "dependencies": { "private": "1" } } },
          "packages": {
            "private": [
              "private@1.0.0",
              "https://registry-with-a-hostname-longer-than-thirty-two.example/private/-/private-1.0.0.tgz",
              {},
              "sha512-private"
            ]
          }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    );

    assert!(matches!(
        result,
        Err(Error::InvalidPackage { key, reason })
            if key == "private" && reason.contains("long private registry hostname")
    ));
}

#[test]
fn rejects_registry_urls_that_embed_credentials() {
    let result = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 3,
          "workspaces": {},
          "packages": {
            "private": [
              "private@1.0.0",
              "https://user:secret@registry.example.test/private/-/private-1.0.0.tgz",
              {},
              "sha512-private"
            ]
          }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    );

    assert!(matches!(
        result,
        Err(Error::InvalidPackage { key, reason })
            if key == "private" && reason.contains("credentials")
    ));
}

#[test]
fn rejects_git_https_urls_that_embed_credentials() {
    let result = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 3,
          "workspaces": {},
          "packages": {
            "git": ["git@git+https://user:secret@git.example.test/repo.git#deadbeef", {}, "deadbeef"]
          }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    );

    assert!(matches!(
        result,
        Err(Error::InvalidPackage { key, reason })
            if key == "git" && reason.contains("credentials")
    ));
}

#[test]
fn supports_every_local_tar_archive_extension_accepted_by_bun() {
    for archive in [
        "package.tgz",
        "package.tar",
        "package.tar.gz",
        "package.TGZ",
    ] {
        let lock = format!(
            r#"{{
              "lockfileVersion": 3,
              "workspaces": {{ "": {{ "name": "app", "dependencies": {{ "local": "{archive}" }} }} }},
              "packages": {{ "local": ["local@{archive}", {{}}, "hash"] }}
            }}"#
        );
        let output =
            convert_lockfile_with_prefetcher(&lock, &ConvertOptions::default(), &NoPrefetch)
                .unwrap();

        assert!(output.contains(&format!(
            "(path \"local@{archive}\" \"{archive}\" null null)"
        )));
    }
}
