//! Integration tests for deterministic `bun.nix` conversion.

use std::sync::Mutex;

use bun2nix::{
    ConvertOptions, Error, Lockfile, Prefetcher, Result, convert_lockfile_with_prefetcher,
};

struct NoPrefetch;

impl Prefetcher for NoPrefetch {
    fn prefetch(&self, source: &str) -> Result<String> {
        panic!("unexpected prefetch for {source}")
    }
}

#[derive(Default)]
struct RecordingPrefetcher {
    sources: Mutex<Vec<String>>,
}

impl Prefetcher for RecordingPrefetcher {
    fn prefetch(&self, source: &str) -> Result<String> {
        self.sources.lock().unwrap().push(source.to_owned());
        Ok("sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".to_owned())
    }
}

fn lockfile(version: u8) -> String {
    format!(
        r#"{{
          "lockfileVersion": {version},
          "workspaces": {{
            "": {{ "name": "root", "devDependencies": {{ "root-only": "1" }} }},
            "apps/web": {{
              "name": "web",
              "dependencies": {{ "native": "1", "shared": "1" }},
              "devDependencies": {{ "tool": "1" }}
            }}
          }},
          "packages": {{
            "native": ["native@2.0.0", "", {{ "os": "linux", "cpu": ["x64", "arm64"] }}, "sha512-native"],
            "root-only": ["root-only@1.0.0", "", {{}}, "sha512-root"],
            "shared": ["shared@1.0.0", "", {{}}, "sha512-shared"],
            "tool": ["tool@3.0.0", "https://npm.example.test/tool/-/tool-3.0.0.tgz", {{}}, "sha512-tool"],
            "web": ["web@workspace:apps/web"]
          }}
        }}"#
    )
}

#[test]
fn renders_canonical_packages_and_lock_metadata() {
    let output =
        convert_lockfile_with_prefetcher(&lockfile(3), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();

    assert!(output.starts_with("# Autogenerated by `bun2nix`"));
    assert!(output.contains("packages = {"));
    assert!(output.contains("\"native@2.0.0\" = fetchurl {"));
    assert!(output.contains("url = \"https://registry.npmjs.org/native/-/native-2.0.0.tgz\";"));
    assert!(output.contains("\"web@workspace:apps/web\" = copyPathToStore (./. + \"/apps/web\");"));
    assert!(output.contains("metadata = {\n    lockfileVersion = 3;"));
    assert!(output.contains("workspacePackages = [ \"web@workspace:apps/web\" ];"));
    assert!(output.contains("\"web\" = [ \"native@2.0.0\" \"shared@1.0.0\" \"tool@3.0.0\" ];"));
    assert!(!output.contains("\"web\" = [ \"root-only@1.0.0\""));
    assert!(output.contains("os = [ \"linux\" ];"));
    assert!(output.contains("cpu = [ \"arm64\" \"x64\" ];"));
    assert!(output.contains("registry = \"npm.example.test\";"));
    assert!(output.contains("source = \"workspace\";\n        local = true;"));
}

#[test]
fn version_one_and_three_render_identically_apart_from_metadata() {
    let version_one =
        convert_lockfile_with_prefetcher(&lockfile(1), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();
    let version_three =
        convert_lockfile_with_prefetcher(&lockfile(3), &ConvertOptions::default(), &NoPrefetch)
            .unwrap();

    assert_eq!(
        version_one.replace("lockfileVersion = 1", "lockfileVersion = 3"),
        version_three
    );
}

#[test]
fn prefetches_direct_tarball_git_and_github_sources() {
    let lock = r#"{
      "lockfileVersion": 1,
      "workspaces": {},
      "packages": {
        "tar": ["tar@https://example.test/tar.tgz", {}],
        "git": ["git@git+https://git.example.test/repo.git#deadbeef", {}, "deadbeef"],
        "git-ssh": ["git-ssh@git+ssh://git@git.example.test/repo.git#facefeed", {}, "facefeed"],
        "github": ["github@github:owner/repo#cafebabe", {}, "owner-repo-cafebabe"]
      }
    }"#;
    let prefetcher = RecordingPrefetcher::default();

    let output =
        convert_lockfile_with_prefetcher(lock, &ConvertOptions::default(), &prefetcher).unwrap();

    assert!(output.contains("\"tar@https://example.test/tar.tgz\" = builtins.fetchTarball {"));
    assert!(output.contains("\"git@git+https://git.example.test/repo.git#deadbeef\" = fetchgit {"));
    assert!(
        output
            .contains("\"git-ssh@git+ssh://git@git.example.test/repo.git#facefeed\" = fetchgit {")
    );
    assert!(output.contains("\"github@github:owner/repo#cafebabe\" = fetchFromGitHub {"));
    assert_eq!(
        *prefetcher.sources.lock().unwrap(),
        [
            "git+https://git.example.test/repo.git?rev=deadbeef",
            "git+ssh://git@git.example.test/repo.git?rev=facefeed",
            "github:owner/repo?ref=cafebabe",
            "https://example.test/tar.tgz",
        ]
    );
}

#[test]
fn parsed_lockfile_closures_are_stable_across_repeated_calls() {
    let lock = Lockfile::parse(&lockfile(3)).unwrap();
    assert_eq!(
        lock.dependency_closures().unwrap(),
        lock.dependency_closures().unwrap()
    );
}

#[test]
fn rejects_local_lockfile_paths_that_escape_the_source_root() {
    let result = convert_lockfile_with_prefetcher(
        r#"{
          "lockfileVersion": 1,
          "workspaces": {},
          "packages": { "escape": ["escape@file:../outside"] }
        }"#,
        &ConvertOptions::default(),
        &NoPrefetch,
    );

    assert!(matches!(result, Err(Error::InvalidPackage { key, .. }) if key == "escape"));
}

#[test]
fn renders_workspace_relative_path_tarballs_as_cacheable_local_sources() {
    let output = convert_lockfile_with_prefetcher(
        include_str!("fixtures/path-local-tarball.lock"),
        &ConvertOptions::default(),
        &NoPrefetch,
    )
    .unwrap();

    assert!(output.contains(
        "\"tar-local@../../vendor/tar-local.tgz\" = copyPathToStore (./. + \"/vendor/tar-local.tgz\");"
    ));
    assert!(output.contains("workspacePackages = [ \"app@workspace:apps/app\" ];"));
    assert!(
        output.contains("\"app\" = [ \"kleur@4.1.5\" \"tar-local@../../vendor/tar-local.tgz\" ];")
    );
    assert!(output.contains("source = \"tarball\";\n        local = false;"));
}

#[test]
fn rejects_workspace_relative_tarballs_that_escape_the_repository() {
    let lockfile = include_str!("fixtures/path-local-tarball.lock")
        .replace("../../vendor/tar-local.tgz", "../../../outside.tgz");

    let result =
        convert_lockfile_with_prefetcher(&lockfile, &ConvertOptions::default(), &NoPrefetch);

    assert!(matches!(result, Err(Error::InvalidPackage { key, .. }) if key == "tar-local"));
}
